services:
  rust:
    image: rust:1.83.0
    volumes:
      - .:/projects
    working_dir: /projects
    environment:
      - USER=user
    networks:
      - gdb-network
    command:
      - /bin/bash
      - -c
      - RUST_LOG=info cargo run --release apps/xv6-riscv/kernel/kernel --elf --base-addr 2147483648 --loop-on -c 100000 -o log/output_kernel.log --gdb 2> log/output_kernel.log
  gdb:
    image: riscv_gdb:latest
    volumes:
      - .:/projects
    working_dir: /projects
    environment:
      - USER=user
    networks:
      - gdb-network
    stdin_open: true
    tty: true
    command:
      riscv64-unknown-elf-gdb apps/xv6-riscv/kernel/kernel

networks:
  gdb-network:
    driver: bridge

