services:
  riscv_dev:
    build:
      context: .
      dockerfile: Dockerfile.riscv_gdb
    image: riscv_gdb:latest
    volumes:
      - .:/projects
    working_dir: /projects
    environment:
      - USER=user
    stdin_open: true
    tty: true


